[tool.poetry]
name = "natsume-simple"
version = "0.1.0"
description = "simple dependency relation search engine for Japanese"
authors = ["Bor Hodošček <dev@bor.space>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
# We keep GiNZA pinned to have reproducible results
ginza = "5.1.2"
ja_ginza = "5.1.2"
ja_ginza_electra = { version = "5.1.2", optional = true }

torch = { version = "^1.13.0", optional = true }
spacy = { version = "^3.4.2", extras = ["cuda-autodetect"], optional = true }
cupy-cuda11x = { version = "^11.2.0", optional = true }

numpy = { version = "1.23.4", python = ">=3.8,<4.0" }
datasets = "~2.6.1"
fastapi = "^0.85.0"
uvicorn = { version = "^0.19.0", extras = ["standard"] }

[tool.poetry.extras]
electra = ["ja_ginza_electra", "torch", "spacy", "cupy-cuda11x"]

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.16.2"
ipywidgets = "^8.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

